<?php
/* 

	DO NOT EDIT THIS FILE!! DOING SO COULD BREAK YOUR INSTALLATION!!!
	
	DEVELOPER NOTE: any plugins or themes that alter this file will be rejected or removed from the Phoenix market.
	Doing so voliolates our developer terms of service.	
	
*/

define( "START_TIME", time() );

define( "VERSION", "0.1" ); //
define( "BUILD", "00000001" );

define( "ROOT", $_SERVER['DOCUMENT_ROOT'] . "phoenix" );
define( "SELF", $_SERVER['PHP_SELF']);
define( "LOCAL_ROOT", "/phoenix" );

define( "THEME_ROOT", ROOT . "/p/" );

date_default_timezone_set( TIMEZONE_SET );

ini_set('display_errors', 'Off');

function phoenixErrorHandler() {
	
	$error_page = file_get_contents( ROOT . "/includes/frontend/phoenix_error.html");
	
	//$file = str_replace("%$def%", "$val", $error_page);
	
	$err = error_get_last();
	
	die(var_dump($err));
	
}

register_shutdown_function("phoenixErrorHandler");